// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_game_event.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ssl_5fgame_5fevent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ssl_5fgame_5fevent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ssl_5fgame_5fevent_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ssl_5fgame_5fevent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ssl_5fgame_5fevent_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_ssl_5fgame_5fevent_2eproto_metadata_getter(int index);
class Game_Event;
struct Game_EventDefaultTypeInternal;
extern Game_EventDefaultTypeInternal _Game_Event_default_instance_;
class Game_Event_Originator;
struct Game_Event_OriginatorDefaultTypeInternal;
extern Game_Event_OriginatorDefaultTypeInternal _Game_Event_Originator_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Game_Event* Arena::CreateMaybeMessage<::Game_Event>(Arena*);
template<> ::Game_Event_Originator* Arena::CreateMaybeMessage<::Game_Event_Originator>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum Game_Event_GameEventType : int {
  Game_Event_GameEventType_UNKNOWN = 0,
  Game_Event_GameEventType_CUSTOM = 1,
  Game_Event_GameEventType_NUMBER_OF_PLAYERS = 2,
  Game_Event_GameEventType_BALL_LEFT_FIELD = 3,
  Game_Event_GameEventType_GOAL = 4,
  Game_Event_GameEventType_KICK_TIMEOUT = 5,
  Game_Event_GameEventType_NO_PROGRESS_IN_GAME = 6,
  Game_Event_GameEventType_BOT_COLLISION = 7,
  Game_Event_GameEventType_MULTIPLE_DEFENDER = 8,
  Game_Event_GameEventType_MULTIPLE_DEFENDER_PARTIALLY = 9,
  Game_Event_GameEventType_ATTACKER_IN_DEFENSE_AREA = 10,
  Game_Event_GameEventType_ICING = 11,
  Game_Event_GameEventType_BALL_SPEED = 12,
  Game_Event_GameEventType_ROBOT_STOP_SPEED = 13,
  Game_Event_GameEventType_BALL_DRIBBLING = 14,
  Game_Event_GameEventType_ATTACKER_TOUCH_KEEPER = 15,
  Game_Event_GameEventType_DOUBLE_TOUCH = 16,
  Game_Event_GameEventType_ATTACKER_TO_DEFENCE_AREA = 17,
  Game_Event_GameEventType_DEFENDER_TO_KICK_POINT_DISTANCE = 18,
  Game_Event_GameEventType_BALL_HOLDING = 19,
  Game_Event_GameEventType_INDIRECT_GOAL = 20,
  Game_Event_GameEventType_BALL_PLACEMENT_FAILED = 21,
  Game_Event_GameEventType_CHIP_ON_GOAL = 22
};
bool Game_Event_GameEventType_IsValid(int value);
constexpr Game_Event_GameEventType Game_Event_GameEventType_GameEventType_MIN = Game_Event_GameEventType_UNKNOWN;
constexpr Game_Event_GameEventType Game_Event_GameEventType_GameEventType_MAX = Game_Event_GameEventType_CHIP_ON_GOAL;
constexpr int Game_Event_GameEventType_GameEventType_ARRAYSIZE = Game_Event_GameEventType_GameEventType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Game_Event_GameEventType_descriptor();
template<typename T>
inline const std::string& Game_Event_GameEventType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Game_Event_GameEventType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Game_Event_GameEventType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Game_Event_GameEventType_descriptor(), enum_t_value);
}
inline bool Game_Event_GameEventType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Game_Event_GameEventType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Game_Event_GameEventType>(
    Game_Event_GameEventType_descriptor(), name, value);
}
enum Game_Event_Team : int {
  Game_Event_Team_TEAM_UNKNOWN = 0,
  Game_Event_Team_TEAM_YELLOW = 1,
  Game_Event_Team_TEAM_BLUE = 2
};
bool Game_Event_Team_IsValid(int value);
constexpr Game_Event_Team Game_Event_Team_Team_MIN = Game_Event_Team_TEAM_UNKNOWN;
constexpr Game_Event_Team Game_Event_Team_Team_MAX = Game_Event_Team_TEAM_BLUE;
constexpr int Game_Event_Team_Team_ARRAYSIZE = Game_Event_Team_Team_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Game_Event_Team_descriptor();
template<typename T>
inline const std::string& Game_Event_Team_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Game_Event_Team>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Game_Event_Team_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Game_Event_Team_descriptor(), enum_t_value);
}
inline bool Game_Event_Team_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Game_Event_Team* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Game_Event_Team>(
    Game_Event_Team_descriptor(), name, value);
}
// ===================================================================

class Game_Event_Originator PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game_Event.Originator) */ {
 public:
  inline Game_Event_Originator() : Game_Event_Originator(nullptr) {}
  virtual ~Game_Event_Originator();
  explicit constexpr Game_Event_Originator(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Game_Event_Originator(const Game_Event_Originator& from);
  Game_Event_Originator(Game_Event_Originator&& from) noexcept
    : Game_Event_Originator() {
    *this = ::std::move(from);
  }

  inline Game_Event_Originator& operator=(const Game_Event_Originator& from) {
    CopyFrom(from);
    return *this;
  }
  inline Game_Event_Originator& operator=(Game_Event_Originator&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Game_Event_Originator& default_instance() {
    return *internal_default_instance();
  }
  static inline const Game_Event_Originator* internal_default_instance() {
    return reinterpret_cast<const Game_Event_Originator*>(
               &_Game_Event_Originator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Game_Event_Originator& a, Game_Event_Originator& b) {
    a.Swap(&b);
  }
  inline void Swap(Game_Event_Originator* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Game_Event_Originator* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Game_Event_Originator* New() const final {
    return CreateMaybeMessage<Game_Event_Originator>(nullptr);
  }

  Game_Event_Originator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Game_Event_Originator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Game_Event_Originator& from);
  void MergeFrom(const Game_Event_Originator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Game_Event_Originator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game_Event.Originator";
  }
  protected:
  explicit Game_Event_Originator(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_ssl_5fgame_5fevent_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTeamFieldNumber = 1,
    kBotIdFieldNumber = 2,
  };
  // required .Game_Event.Team team = 1;
  bool has_team() const;
  private:
  bool _internal_has_team() const;
  public:
  void clear_team();
  ::Game_Event_Team team() const;
  void set_team(::Game_Event_Team value);
  private:
  ::Game_Event_Team _internal_team() const;
  void _internal_set_team(::Game_Event_Team value);
  public:

  // optional uint32 botId = 2;
  bool has_botid() const;
  private:
  bool _internal_has_botid() const;
  public:
  void clear_botid();
  ::PROTOBUF_NAMESPACE_ID::uint32 botid() const;
  void set_botid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_botid() const;
  void _internal_set_botid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Game_Event.Originator)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int team_;
  ::PROTOBUF_NAMESPACE_ID::uint32 botid_;
  friend struct ::TableStruct_ssl_5fgame_5fevent_2eproto;
};
// -------------------------------------------------------------------

class Game_Event PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Game_Event) */ {
 public:
  inline Game_Event() : Game_Event(nullptr) {}
  virtual ~Game_Event();
  explicit constexpr Game_Event(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Game_Event(const Game_Event& from);
  Game_Event(Game_Event&& from) noexcept
    : Game_Event() {
    *this = ::std::move(from);
  }

  inline Game_Event& operator=(const Game_Event& from) {
    CopyFrom(from);
    return *this;
  }
  inline Game_Event& operator=(Game_Event&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Game_Event& default_instance() {
    return *internal_default_instance();
  }
  static inline const Game_Event* internal_default_instance() {
    return reinterpret_cast<const Game_Event*>(
               &_Game_Event_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Game_Event& a, Game_Event& b) {
    a.Swap(&b);
  }
  inline void Swap(Game_Event* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Game_Event* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Game_Event* New() const final {
    return CreateMaybeMessage<Game_Event>(nullptr);
  }

  Game_Event* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Game_Event>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Game_Event& from);
  void MergeFrom(const Game_Event& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Game_Event* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Game_Event";
  }
  protected:
  explicit Game_Event(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_ssl_5fgame_5fevent_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  typedef Game_Event_Originator Originator;

  typedef Game_Event_GameEventType GameEventType;
  static constexpr GameEventType UNKNOWN =
    Game_Event_GameEventType_UNKNOWN;
  static constexpr GameEventType CUSTOM =
    Game_Event_GameEventType_CUSTOM;
  static constexpr GameEventType NUMBER_OF_PLAYERS =
    Game_Event_GameEventType_NUMBER_OF_PLAYERS;
  static constexpr GameEventType BALL_LEFT_FIELD =
    Game_Event_GameEventType_BALL_LEFT_FIELD;
  static constexpr GameEventType GOAL =
    Game_Event_GameEventType_GOAL;
  static constexpr GameEventType KICK_TIMEOUT =
    Game_Event_GameEventType_KICK_TIMEOUT;
  static constexpr GameEventType NO_PROGRESS_IN_GAME =
    Game_Event_GameEventType_NO_PROGRESS_IN_GAME;
  static constexpr GameEventType BOT_COLLISION =
    Game_Event_GameEventType_BOT_COLLISION;
  static constexpr GameEventType MULTIPLE_DEFENDER =
    Game_Event_GameEventType_MULTIPLE_DEFENDER;
  static constexpr GameEventType MULTIPLE_DEFENDER_PARTIALLY =
    Game_Event_GameEventType_MULTIPLE_DEFENDER_PARTIALLY;
  static constexpr GameEventType ATTACKER_IN_DEFENSE_AREA =
    Game_Event_GameEventType_ATTACKER_IN_DEFENSE_AREA;
  static constexpr GameEventType ICING =
    Game_Event_GameEventType_ICING;
  static constexpr GameEventType BALL_SPEED =
    Game_Event_GameEventType_BALL_SPEED;
  static constexpr GameEventType ROBOT_STOP_SPEED =
    Game_Event_GameEventType_ROBOT_STOP_SPEED;
  static constexpr GameEventType BALL_DRIBBLING =
    Game_Event_GameEventType_BALL_DRIBBLING;
  static constexpr GameEventType ATTACKER_TOUCH_KEEPER =
    Game_Event_GameEventType_ATTACKER_TOUCH_KEEPER;
  static constexpr GameEventType DOUBLE_TOUCH =
    Game_Event_GameEventType_DOUBLE_TOUCH;
  static constexpr GameEventType ATTACKER_TO_DEFENCE_AREA =
    Game_Event_GameEventType_ATTACKER_TO_DEFENCE_AREA;
  static constexpr GameEventType DEFENDER_TO_KICK_POINT_DISTANCE =
    Game_Event_GameEventType_DEFENDER_TO_KICK_POINT_DISTANCE;
  static constexpr GameEventType BALL_HOLDING =
    Game_Event_GameEventType_BALL_HOLDING;
  static constexpr GameEventType INDIRECT_GOAL =
    Game_Event_GameEventType_INDIRECT_GOAL;
  static constexpr GameEventType BALL_PLACEMENT_FAILED =
    Game_Event_GameEventType_BALL_PLACEMENT_FAILED;
  static constexpr GameEventType CHIP_ON_GOAL =
    Game_Event_GameEventType_CHIP_ON_GOAL;
  static inline bool GameEventType_IsValid(int value) {
    return Game_Event_GameEventType_IsValid(value);
  }
  static constexpr GameEventType GameEventType_MIN =
    Game_Event_GameEventType_GameEventType_MIN;
  static constexpr GameEventType GameEventType_MAX =
    Game_Event_GameEventType_GameEventType_MAX;
  static constexpr int GameEventType_ARRAYSIZE =
    Game_Event_GameEventType_GameEventType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  GameEventType_descriptor() {
    return Game_Event_GameEventType_descriptor();
  }
  template<typename T>
  static inline const std::string& GameEventType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, GameEventType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function GameEventType_Name.");
    return Game_Event_GameEventType_Name(enum_t_value);
  }
  static inline bool GameEventType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      GameEventType* value) {
    return Game_Event_GameEventType_Parse(name, value);
  }

  typedef Game_Event_Team Team;
  static constexpr Team TEAM_UNKNOWN =
    Game_Event_Team_TEAM_UNKNOWN;
  static constexpr Team TEAM_YELLOW =
    Game_Event_Team_TEAM_YELLOW;
  static constexpr Team TEAM_BLUE =
    Game_Event_Team_TEAM_BLUE;
  static inline bool Team_IsValid(int value) {
    return Game_Event_Team_IsValid(value);
  }
  static constexpr Team Team_MIN =
    Game_Event_Team_Team_MIN;
  static constexpr Team Team_MAX =
    Game_Event_Team_Team_MAX;
  static constexpr int Team_ARRAYSIZE =
    Game_Event_Team_Team_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Team_descriptor() {
    return Game_Event_Team_descriptor();
  }
  template<typename T>
  static inline const std::string& Team_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Team>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Team_Name.");
    return Game_Event_Team_Name(enum_t_value);
  }
  static inline bool Team_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Team* value) {
    return Game_Event_Team_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 3,
    kOriginatorFieldNumber = 2,
    kGameEventTypeFieldNumber = 1,
  };
  // optional string message = 3;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // optional .Game_Event.Originator originator = 2;
  bool has_originator() const;
  private:
  bool _internal_has_originator() const;
  public:
  void clear_originator();
  const ::Game_Event_Originator& originator() const;
  ::Game_Event_Originator* release_originator();
  ::Game_Event_Originator* mutable_originator();
  void set_allocated_originator(::Game_Event_Originator* originator);
  private:
  const ::Game_Event_Originator& _internal_originator() const;
  ::Game_Event_Originator* _internal_mutable_originator();
  public:
  void unsafe_arena_set_allocated_originator(
      ::Game_Event_Originator* originator);
  ::Game_Event_Originator* unsafe_arena_release_originator();

  // required .Game_Event.GameEventType gameEventType = 1;
  bool has_gameeventtype() const;
  private:
  bool _internal_has_gameeventtype() const;
  public:
  void clear_gameeventtype();
  ::Game_Event_GameEventType gameeventtype() const;
  void set_gameeventtype(::Game_Event_GameEventType value);
  private:
  ::Game_Event_GameEventType _internal_gameeventtype() const;
  void _internal_set_gameeventtype(::Game_Event_GameEventType value);
  public:

  // @@protoc_insertion_point(class_scope:Game_Event)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::Game_Event_Originator* originator_;
  int gameeventtype_;
  friend struct ::TableStruct_ssl_5fgame_5fevent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Game_Event_Originator

// required .Game_Event.Team team = 1;
inline bool Game_Event_Originator::_internal_has_team() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Game_Event_Originator::has_team() const {
  return _internal_has_team();
}
inline void Game_Event_Originator::clear_team() {
  team_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::Game_Event_Team Game_Event_Originator::_internal_team() const {
  return static_cast< ::Game_Event_Team >(team_);
}
inline ::Game_Event_Team Game_Event_Originator::team() const {
  // @@protoc_insertion_point(field_get:Game_Event.Originator.team)
  return _internal_team();
}
inline void Game_Event_Originator::_internal_set_team(::Game_Event_Team value) {
  assert(::Game_Event_Team_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  team_ = value;
}
inline void Game_Event_Originator::set_team(::Game_Event_Team value) {
  _internal_set_team(value);
  // @@protoc_insertion_point(field_set:Game_Event.Originator.team)
}

// optional uint32 botId = 2;
inline bool Game_Event_Originator::_internal_has_botid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Game_Event_Originator::has_botid() const {
  return _internal_has_botid();
}
inline void Game_Event_Originator::clear_botid() {
  botid_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Game_Event_Originator::_internal_botid() const {
  return botid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Game_Event_Originator::botid() const {
  // @@protoc_insertion_point(field_get:Game_Event.Originator.botId)
  return _internal_botid();
}
inline void Game_Event_Originator::_internal_set_botid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  botid_ = value;
}
inline void Game_Event_Originator::set_botid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_botid(value);
  // @@protoc_insertion_point(field_set:Game_Event.Originator.botId)
}

// -------------------------------------------------------------------

// Game_Event

// required .Game_Event.GameEventType gameEventType = 1;
inline bool Game_Event::_internal_has_gameeventtype() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Game_Event::has_gameeventtype() const {
  return _internal_has_gameeventtype();
}
inline void Game_Event::clear_gameeventtype() {
  gameeventtype_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::Game_Event_GameEventType Game_Event::_internal_gameeventtype() const {
  return static_cast< ::Game_Event_GameEventType >(gameeventtype_);
}
inline ::Game_Event_GameEventType Game_Event::gameeventtype() const {
  // @@protoc_insertion_point(field_get:Game_Event.gameEventType)
  return _internal_gameeventtype();
}
inline void Game_Event::_internal_set_gameeventtype(::Game_Event_GameEventType value) {
  assert(::Game_Event_GameEventType_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  gameeventtype_ = value;
}
inline void Game_Event::set_gameeventtype(::Game_Event_GameEventType value) {
  _internal_set_gameeventtype(value);
  // @@protoc_insertion_point(field_set:Game_Event.gameEventType)
}

// optional .Game_Event.Originator originator = 2;
inline bool Game_Event::_internal_has_originator() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || originator_ != nullptr);
  return value;
}
inline bool Game_Event::has_originator() const {
  return _internal_has_originator();
}
inline void Game_Event::clear_originator() {
  if (originator_ != nullptr) originator_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::Game_Event_Originator& Game_Event::_internal_originator() const {
  const ::Game_Event_Originator* p = originator_;
  return p != nullptr ? *p : reinterpret_cast<const ::Game_Event_Originator&>(
      ::_Game_Event_Originator_default_instance_);
}
inline const ::Game_Event_Originator& Game_Event::originator() const {
  // @@protoc_insertion_point(field_get:Game_Event.originator)
  return _internal_originator();
}
inline void Game_Event::unsafe_arena_set_allocated_originator(
    ::Game_Event_Originator* originator) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(originator_);
  }
  originator_ = originator;
  if (originator) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Game_Event.originator)
}
inline ::Game_Event_Originator* Game_Event::release_originator() {
  _has_bits_[0] &= ~0x00000002u;
  ::Game_Event_Originator* temp = originator_;
  originator_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Game_Event_Originator* Game_Event::unsafe_arena_release_originator() {
  // @@protoc_insertion_point(field_release:Game_Event.originator)
  _has_bits_[0] &= ~0x00000002u;
  ::Game_Event_Originator* temp = originator_;
  originator_ = nullptr;
  return temp;
}
inline ::Game_Event_Originator* Game_Event::_internal_mutable_originator() {
  _has_bits_[0] |= 0x00000002u;
  if (originator_ == nullptr) {
    auto* p = CreateMaybeMessage<::Game_Event_Originator>(GetArena());
    originator_ = p;
  }
  return originator_;
}
inline ::Game_Event_Originator* Game_Event::mutable_originator() {
  // @@protoc_insertion_point(field_mutable:Game_Event.originator)
  return _internal_mutable_originator();
}
inline void Game_Event::set_allocated_originator(::Game_Event_Originator* originator) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete originator_;
  }
  if (originator) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(originator);
    if (message_arena != submessage_arena) {
      originator = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, originator, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  originator_ = originator;
  // @@protoc_insertion_point(field_set_allocated:Game_Event.originator)
}

// optional string message = 3;
inline bool Game_Event::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Game_Event::has_message() const {
  return _internal_has_message();
}
inline void Game_Event::clear_message() {
  message_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Game_Event::message() const {
  // @@protoc_insertion_point(field_get:Game_Event.message)
  return _internal_message();
}
inline void Game_Event::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:Game_Event.message)
}
inline std::string* Game_Event::mutable_message() {
  // @@protoc_insertion_point(field_mutable:Game_Event.message)
  return _internal_mutable_message();
}
inline const std::string& Game_Event::_internal_message() const {
  return message_.Get();
}
inline void Game_Event::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Game_Event::set_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Game_Event.message)
}
inline void Game_Event::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:Game_Event.message)
}
inline void Game_Event::set_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Game_Event.message)
}
inline std::string* Game_Event::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000001u;
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Game_Event::release_message() {
  // @@protoc_insertion_point(field_release:Game_Event.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Game_Event::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Game_Event.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Game_Event_GameEventType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Game_Event_GameEventType>() {
  return ::Game_Event_GameEventType_descriptor();
}
template <> struct is_proto_enum< ::Game_Event_Team> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Game_Event_Team>() {
  return ::Game_Event_Team_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ssl_5fgame_5fevent_2eproto
