sudo: required
language: cpp
os: linux
dist: trusty
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo ./installDeps.sh
  - 'if [ "$CMAKE_ARGS" = "-DUSE_QT5=True" ]; then sudo apt-get install -qq qtbase5-dev; fi'

env:
  - CMAKE_ARGS=""
  - CMAKE_ARGS="-DUSE_QT5=True"

script:
  - mkdir -p build
  - cd build
  - cmake $CMAKE_ARGS ..
  - make
